## 2. METRIC

In [2]:
import pandas as pd

parking= pd.read_csv("finalproject.csv")
parking.head(15)

         neighborhood                          school  enrolled_students
0    Allegheny Center                           Other                 50
1    Allegheny Center          PITTSBURGH KING PreK-8                 34
2           Allentown                           Other                 96
3           Allentown     PITTSBURGH GRANDVIEW PreK-5                 76
4           Allentown      PITTSBURGH SOUTH HILLS 6-8                 50
5           Allentown  PITTSBURGH CARRICK HIGH SCHOOL                 35
6           Allentown       PITTSBURGH CARMALT PreK-8                 21
7           Allentown        PITTSBURGH OBAMA IB 6-12                 11
8           Arlington     PITTSBURGH ARLINGTON PreK-8                 61
9           Arlington                           Other                 56
10          Arlington  PITTSBURGH CARRICK HIGH SCHOOL                 36
11          Arlington       PITTSBURGH CARMALT PreK-8                 18
12          Arlington         PITTSBURGH PHILLIPS K-5                 15
13  Arlington Heights     PITTSBURGH ARLINGTON PreK-8                 16
14  Arlington Heights                           Other                 11